/* Goals dashboard helpers regression tests — node:test (stdlib), no framework.
 * Imports the REAL static/format.js the SPA uses and pins the mirrors against
 * the Python reference implementations (rewards.checkpoint_thresholds,
 * units.kg_to_stone): every non-trivial expected value below was generated by
 * running the Python function on the same input, so a drift in the JS mirror
 * fails here. */
import { test } from "node:test";
import assert from "node:assert/strict";
import format from "../../static/format.js";

const { goalProgress, checkpointThresholds, kgToImperial } = format;

test("goalProgress returns 0.5 for half-way progress", () => {
  assert.equal(goalProgress(100, 90, 80), 0.5);
});

test("goalProgress returns 0 at the start (no loss yet)", () => {
  assert.equal(goalProgress(100, 100, 80), 0);
});

test("goalProgress returns 1 at the target", () => {
  assert.equal(goalProgress(100, 80, 80), 1);
});

test("goalProgress clamps overshoot to 1.0", () => {
  assert.equal(goalProgress(100, 78, 80), 1);
  assert.equal(goalProgress(100, 50, 80), 1);
});

test("goalProgress clamps weight gain to 0", () => {
  assert.equal(goalProgress(100, 110, 80), 0);
});

test("goalProgress is null when any input is missing", () => {
  assert.equal(goalProgress(null, 90, 80), null);
  assert.equal(goalProgress(100, null, 80), null);
  assert.equal(goalProgress(100, 90, null), null);
  assert.equal(goalProgress(undefined, 90, 80), null);
});

test("goalProgress is null when baseline <= target (no loss goal)", () => {
  assert.equal(goalProgress(80, 78, 100), null);
  assert.equal(goalProgress(100, 100, 100), null);
});

test("checkpointThresholds drift pin mirrors rewards.py for (100, 80)", () => {
  assert.deepEqual(checkpointThresholds(100, 80), [98, 95, 90, 85, 80]);
});

test("checkpointThresholds mirrors rewards.py 4dp rounding on a non-trivial case", () => {
  // Generated from rewards.checkpoint_thresholds(95.4, 72.1): the values the
  // Python reference produces with round(x, 4).
  assert.deepEqual(checkpointThresholds(95.4, 72.1), [93.07, 89.575, 83.75, 77.925, 72.1]);
});

test("checkpointThresholds returns [] for null inputs", () => {
  assert.deepEqual(checkpointThresholds(null, 80), []);
  assert.deepEqual(checkpointThresholds(100, null), []);
  assert.deepEqual(checkpointThresholds(undefined, 80), []);
});

test("checkpointThresholds returns [] when target >= baseline", () => {
  assert.deepEqual(checkpointThresholds(80, 100), []);
  assert.deepEqual(checkpointThresholds(100, 100), []);
});

test("kgToImperial mirrors units.kg_to_stone for 82.5 kg", () => {
  assert.deepEqual(kgToImperial(82.5), {
    lb: 181.8813662985,
    stone: 12,
    stoneLb: 13.881366298500012,
  });
});

test("kgToImperial snaps the 14-lb boundary carry like units.py", () => {
  // 63.502931800000006 kg -> 139.9999999969026 lb, a hair under 10 st; the
  // epsilon snap must land on (10, 0.0), not (9, 13.9999999969026).
  assert.deepEqual(kgToImperial(63.502931800000006), {
    lb: 139.9999999969026,
    stone: 10,
    stoneLb: 0,
  });
});

test("kgToImperial is null for null input", () => {
  assert.equal(kgToImperial(null), null);
  assert.equal(kgToImperial(undefined), null);
});
